        <div class="siteMenu" align="center">
                <div class="contentWidth">
                        <div class="menuLinks">
                                <table class="width" cellpadding="0" cellspacing="0">
                                        <tbody>
                                        <tr>
                                                <td class="tall_menu"></td>
                                                        <td>
                                                                <a href="about" title="About Us" class="menu_button"><img src="/images/page_white_text.png" />About us</a>

                                                        </td>
                                                        <td>
                                                                <a href="how-it-works" title="How It Works" class="menu_button"><img src="/images/wrench.png" />How it works</a>
                                                        </td>
                                                        <td>
                                                                <a href="prices" title="Prices" class="menu_button"><img src="/images/money_dollar.png" />Prices</a>
                                                        </td>
                                                        <td>
                                                                <a href="services" title="Browse Designs" class="menu_button"><img src="/images/computer_go.png" />Services</a>

                                                        </td>
                                                        <td>
                                                                <a href="faq" title="Faq" class="menu_button"><img src="/images/comments.png" />FAQ</a>

                                                        </td>
                                                        <td>
                                                                <a href="contact" title="Contact Us" rel="nofollow" class="menu_button"><img src="/images/phone.png" />Contact us</a>
                                                        </td>
                                                        <td>
                                                                <a href="register" title="Register" rel="nofollow" class="menu_button"><img src="/images/script.png" />Register</a>
                                                        </td>
                                                         <td>
                                                                <a href="login" title="Login" rel="nofollow" class="menu_button"><img src="/images/lock_go.png" />Login</a>
                                                        </td>
                                                        <td class="tall_menu"></td>
                                                </tr>
                                        </tbody>
                                </table>
                        </div>
                </div>
        </div>

